apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: distoreclusters.distore.io
spec:
  group: distore.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 100
              image:
                type: string
              httpPort:
                type: integer
                default: 8080
              prometheusPort:
                type: integer
                default: 9090
              dataDir:
                type: string
                default: "/data"
              storage:
                type: object
                properties:
                  size:
                    type: string
                    default: "10Gi"
                  storageClass:
                    type: string
              auth:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  secretName:
                    type: string
              tls:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  secretName:
                    type: string
              multiCloud:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  dataCenters:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        region:
                          type: string
                        priority:
                          type: integer
                        replicaCount:
                          type: integer
                  edgeNodes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        location:
                          type: string
                        cacheOnly:
                          type: boolean
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "512Mi"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Running", "Failed"]
              readyReplicas:
                type: integer
              totalReplicas:
                type: integer
              nodes:
                type: array
                items:
                  type: string
    subresources:
      status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distore-operator
  namespace: distore-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distore-operator
  template:
    metadata:
      labels:
        app: distore-operator
    spec:
      serviceAccountName: distore-operator
      containers:
      - name: operator
        image: distore/operator:latest
        ports:
        - containerPort: 8080
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "distore-operator"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: distore-operator
  namespace: distore-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distore-operator
rules:
- apiGroups: ["distore.io"]
  resources: ["distoreclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: distore-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: distore-operator
subjects:
- kind: ServiceAccount
  name: distore-operator
  namespace: distore-system

